/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    String s3;
    int s4;
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namef = new javax.swing.JTextField();
        passwordf = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        Name_er = new javax.swing.JLabel();
        Pass_er = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("Login");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 30, 150, 19);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        namef.setBackground(new java.awt.Color(0, 204, 204));
        namef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                namefKeyReleased(evt);
            }
        });

        passwordf.setBackground(new java.awt.Color(0, 204, 204));
        passwordf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfActionPerformed(evt);
            }
        });
        passwordf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordfKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setForeground(new java.awt.Color(51, 51, 0));
        jButton1.setText("Login");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Name_er.setForeground(new java.awt.Color(255, 255, 255));
        Name_er.setText("Name is required");

        Pass_er.setForeground(new java.awt.Color(255, 255, 255));
        Pass_er.setText("Password is required");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name_er)
                            .addComponent(namef, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Pass_er)
                        .addComponent(passwordf, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(namef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name_er)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pass_er)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("oracle.jdbc.driver.OracleDriver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register1.class.getName()).log(Level.SEVERE, null, ex);
        }

        
            //step2 create  the connection object

            Connection con = null;
            try{
                con = DriverManager.getConnection(
                        "jdbc:oracle:thin:@localhost:1521:xe","afifa","123");
                CallableStatement cstmt = con.prepareCall("{call dbms_output.enable(32000) }");
cstmt.execute();
            PreparedStatement ps;
                ps = con.prepareStatement(
                     "DECLARE\n" +
                            "id1 NUMBER;\n" +
                            "result NUMBER;\n" +
                            "BEGIN\n" +
                            "get_id(?, id1);\n" +
                            "password_match(?, id1, result);\n" +
                            "dbms_output.put_line(result);\n"+
                            "END;\n");    
                PreparedStatement p2;
                p2 = con.prepareStatement(
                     "DECLARE\n" +
"id1 NUMBER;\n" +
"BEGIN\n" +
"get_id('Afifa', id1);\n" +
"dbms_output.put_line(id1);\n" +
"END;\n");   
                 PreparedStatement p3;
                p3 = con.prepareStatement(
                     "DECLARE\n" +
"id2 varchar2(20);\n" +
"BEGIN\n" +
"make_user_id(?, id2);\n" +
"dbms_output.put_line(id2);\n" +
"END;");   
                
               // PreparedStatement p2;
            //p2 = con.prepareStatement
                           // ("SELECT ID FROM PAYER WHERE NAME=?");
                           
                      String s1=namef.getText();
            
            /*p2.setString(1,s1 );
           ResultSet r2;
            r2=p2.executeQuery();
            while(r2.next()){
            s3= r2.getString(1);
            }
            }
            catch (SQLException ex) {
            Logger.getLogger(Register1.class.getName()).log(Level.SEVERE, null, ex);
        }
            try{
                ps.setString(1,s3 );
                ResultSet rs;
            rs=ps.executeQuery();
            while(rs.next()){
            s4= rs.getString(1);
            
            }*/
        String s2=passwordf.getText();
                ps.setString(1,s1 );
                ps.setString(2,s2 );
               // ResultSet rs;
               
                ps.execute();
            //rs=ps.executeQuery();
            
            cstmt = con.prepareCall("{call dbms_output.get_line(?, ?)}");
cstmt.registerOutParameter(1,java.sql.Types.VARCHAR);
cstmt.registerOutParameter(2,java.sql.Types.NUMERIC);
cstmt.execute();
    String line = cstmt.getString(1);
    int status = cstmt.getInt(2);
   
    if (line != null && status == 0)
    {
        //System.out.println(line);
       
    }
   
           /* while(rs.next()){
            s4= rs.getInt(1);;
            System.out.println("after get int");
            }*/
            //String s2=jPasswordField1.getText();
            if(namef.getText().trim().isEmpty() && passwordf.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(null, "Name and password field are empty");
         Name_er.setText("name is required");
         Pass_er.setText("password is required");
        }
        else if(namef.getText().trim().isEmpty())
        {
         JOptionPane.showMessageDialog(null, "Name field is empty");
         Name_er.setText("name is empty");
        }
        else if(passwordf.getText().trim().isEmpty())
        {
         JOptionPane.showMessageDialog(null, "Password field is empty");
         Pass_er.setText("password is empty");
        }
       
           
           // if(s2 == null ? s4 == null : s2.equals(s4))
          
           if("1" == null ? line == null : line.equals("1"))
            {
               
                 p2.execute();
                 cstmt.execute();
    String line1 = cstmt.getString(1);
    int status1 = cstmt.getInt(2);
   
    if (line1 != null && status1 == 0)
    {
        int p3_id=Integer.parseInt(line1);
        p3.setString(1,line1 );
         p3.execute();
                 cstmt.execute();
    String line2 = cstmt.getString(1);
    int status2 = cstmt.getInt(2);
    
   
    if (line2 != null && status2 == 0)
    {
        JOptionPane.showMessageDialog(null, "You have entered as User "+line2+ "\n");
    }
       
            welcome w1=new welcome(Integer.parseInt(line1));
            //System.out.println(s3);
        w1.setVisible(true);
        w1.pack();
        //w1.setLocationRelativeTo(null)
        this.dispose();
        w1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
                
        
            }
            else{
               JOptionPane.showMessageDialog(null, "Username and password do not match");
            }
             
           
            

        } catch (SQLException ex) {
            Logger.getLogger(Register1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void namefKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namefKeyReleased
        // TODO add your handling code here:
        Name_er.setText("");
    }//GEN-LAST:event_namefKeyReleased

    private void passwordfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordfKeyReleased
        // TODO add your handling code here:
        Pass_er.setText("");
    }//GEN-LAST:event_passwordfKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name_er;
    private javax.swing.JLabel Pass_er;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namef;
    private javax.swing.JPasswordField passwordf;
    // End of variables declaration//GEN-END:variables
}
