/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author User
 */

public class Register1 extends javax.swing.JFrame {
private int regCount;
public Connection con;
public PreparedStatement p3, p2, ps, p4;
    /**
     * Creates new form Register
     */
    public Register1() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jmail = new javax.swing.JTextField();
        regmouse = new javax.swing.JButton();
        jname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jpass = new javax.swing.JPasswordField();
        jpass2 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        jmail.setBackground(new java.awt.Color(0, 204, 204));

        regmouse.setBackground(new java.awt.Color(0, 153, 153));
        regmouse.setForeground(new java.awt.Color(51, 51, 0));
        regmouse.setText("Register");
        regmouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regmouseMouseClicked(evt);
            }
        });
        regmouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regmouseActionPerformed(evt);
            }
        });

        jname.setBackground(new java.awt.Color(0, 204, 204));
        jname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnameActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Retype Password:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Emai ID:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Already have an account? Login!");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jpass.setBackground(new java.awt.Color(0, 204, 204));

        jpass2.setBackground(new java.awt.Color(0, 204, 204));
        jpass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpass2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regmouse)
                .addGap(44, 44, 44))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jname, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jmail, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jpass)
                    .addComponent(jpass2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jmail, jname});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jpass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regmouse)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jmail, jname});

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("Registration form");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 30, 150, 19);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regmouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regmouseActionPerformed
      
    try {
        
        try {
            // TODO add your handling code here:
            Class.forName("oracle.jdbc.driver.OracleDriver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        try {
            con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe","afifa","123");
        } catch (SQLException ex) {
            Logger.getLogger(Register1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            p2 = con.prepareStatement
                                    ("INSERT INTO password VALUES(?, ?)");
        } catch (SQLException ex) {
            Logger.getLogger(Register1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            ps = con.prepareStatement
                                ("INSERT INTO payer VALUES(?, ?, ?)");
        } catch (SQLException ex) {
            Logger.getLogger(Register1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            p3 = con.prepareStatement
                                    ("SELECT seq_person.nextval from dual");
        } catch (SQLException ex) {
            Logger.getLogger(Register1.class.getName()).log(Level.SEVERE, null, ex);
        }
        PreparedStatement p5;
                p5 = con.prepareStatement(
                     "DECLARE\n" +
"id2 varchar2(20);\n" +
"BEGIN\n" +
"make_user_id(?, id2);\n" +
"dbms_output.put_line(id2);\n" +
"END;");   
               PreparedStatement p6;
                p6 = con.prepareStatement(
                     "COMMIT");   
                CallableStatement cstmt = con.prepareCall("{call dbms_output.enable(32000) }");
cstmt.execute();
        ResultSet rs;
        
        
        rs=p3.executeQuery();
        while(rs.next()){
            regCount = rs.getInt(1);
        }
        System.out.println("initial reg count"+ regCount);
        
        
        String s1=jmail.getText();
        String s2=jname.getText();
        String s3=jpass.getText();
        String s4=jpass2.getText();
        String s5=Integer.toString(regCount);
        
        //System.out.println(s5);
        if(jname.getText().trim().isEmpty() ||jpass.getText().trim().isEmpty()||jmail.getText().trim().isEmpty()||jpass2.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter data in all fields");
        }
        else{
            if(s4 == null ? s3 == null : s4.equals(s3)){
                
                //ps.setString(1, "SEQ_PERSON.NEXTVAL");
                //p2.setString(1,"SEQ_PERSON.NEXTVAL" );
                
                
                try{
                    p2.setString(1, s5);
                    p2.setString(2, s3 );
                }catch (SQLException ex)
                {System.out.println("1");
                }
                try{
                    
                    p2.execute();
                }catch (SQLException ex)
                {System.out.println("2error");
                }
                try{
                    ps.setString(1, s5);
                }catch (SQLException ex)
                {System.out.println("3");
                }
                try{
                    ps.setString(2, s2);
                }
                catch (SQLException ex)
                {System.out.println("4");
                }
                try{
                    ps.setString(3, s1);
                    ps.execute();
                p6.execute();}
                catch (SQLException ex)
                {
                }
                
                p5.setString(1, s5);
               
                 p5.execute();
                
                 cstmt = con.prepareCall("{call dbms_output.get_line(?, ?)}");
cstmt.registerOutParameter(1,java.sql.Types.VARCHAR);
cstmt.registerOutParameter(2,java.sql.Types.NUMERIC);
cstmt.execute();
String line = cstmt.getString(1);
    int status = cstmt.getInt(2);
   
    if (line != null && status == 0)
    {
     
       JOptionPane.showMessageDialog(null, "You have registered sucessefully!\n Your Unique User ID is\n "+ line +"!");
    }
                
                 p4 = con.prepareStatement
                                    ("insert into scoreboard values(?, 0, 0)");
                 p4.setString(1, s5);
                 p4.execute();
                welcome w1=new welcome((regCount));
        w1.setVisible(true);
        w1.pack();
        //w1.setLocationRelativeTo(null)
        this.dispose();
        w1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Please enter same password in both fields");
            }
        }
        
    } catch (SQLException ex) {
        Logger.getLogger(Register1.class.getName()).log(Level.SEVERE, null, ex);
    }
       
    }//GEN-LAST:event_regmouseActionPerformed

    private void jnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnameActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        login l1=new login();
        l1.setVisible(true);
        l1.pack();
        //11.setLocationRelativeTo(null)
        this.dispose();
        l1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void regmouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regmouseMouseClicked
        // TODO add your handling code here:
       
            
    }//GEN-LAST:event_regmouseMouseClicked

    private void jpass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpass2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register1().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jmail;
    private javax.swing.JTextField jname;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JPasswordField jpass2;
    private javax.swing.JButton regmouse;
    // End of variables declaration//GEN-END:variables
}
